#!/usr/bin/python
import rospy
from geometry_msgs.msg import Twist

def callback(data):
    rospy.loginfo("linear : [x=%f, y=%f, z=%f] et angular [x=%f, y=%f, z=%f]" % (data.linear.x,data.linear.y,data.linear.z, data.angular.x,data.angular.y,data.angular.z))
    print("Dans le callback")

    #modif de la data avant de l'envoyer
    data.linear.x = 42
    data.angular.x = 42
    talker(data)

def talker(data):
    pub = rospy.Publisher('turtle1/cmd_vel_mod', Twist, queue_size=1)
    pub.publish(data)
    print("Dans le talker")

def listener():
    rospy.init_node('turtlePYM')
    print("Dans le listener")
    rospy.Subscriber("cmd_DF", Twist, callback)
    rospy.Publisher("/turtle1/cmd_vel_mod", Twist, queue_size=1)

    #permet a python de ne pas s'arreter
    rospy.spin()

if __name__=='__main__':
    listener()
